# -*- coding: utf-8 -*-
"""Lab5. Programming Paradigms Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfzaC8oUBmrva8_Uf5LjQb8cJL0A1IAg

# Lab5. Programming Paradigms Comparison

**Student Name:** Gonzalez Alvarado Maximiliano   
**Group:** __3A__________________________________  
**Date:** _____20/05/26___________________  

---

# Objective

You will solve the same problem using different programming paradigms.

The goal is to understand how the way you think and structure a solution changes depending on the paradigm.



# Required Paradigms

You must implement the solution using ALL of the following paradigms:

1. Imperative Programming  
2. Structured Programming (functions + control structures)  
3. Modular Programming  
4. Object-Oriented Programming (OOP)  
5. Functional Programming (basic level)


# Important Rules

- The SAME problem must be used in all paradigms.
- You must NOT copy-paste the same solution with small changes.
- Each paradigm must show a different way of structuring the solution.
- Each section must include:
  - explanation in your own words
  - working code
  - a personal modification
  - a short reflection


# Problem Description

Describe the problem you will solve:

```text
A system that calculates the average grade of students and determines if they pass or fail.

# 1. 1. Imperative Programming  

## Brief Explanation
it sums up the grades and divides it by the ammount of grades

## Code Example
Complete the steps
"""

# Given data
grades = [70, 80, 90]
total = 0

# 1. Calculate sum using a loop
for i in grades:
  total += 1
  average = total /len(grades)

if average >= 70:
  print("pass")
else:
  print("fail")

print("Average: ", average)

pass
# 2. Compute average
# 3. Print result

"""## Your Modification


```
#given data
grades= [70,80,90]
total = 0

#1. Calculate sum using a loop
for i in grades:
  total += i
average = total /len(grades)

#2. calculate the average
if average >= 70:
  print("Pass")
else:
  print("Fail")

print("Average: ", average)
```


What did you change and why?

I changed  the 1 in 'total += 1" to a i so it can properly run


## Reflection
What did you learn from this approach and how does it compare to others?

I learnt that small mistakes can lead to the code not working whatsoever
"""

#given data
grades= [70,80,90]
total = 0

#1. Calculate sum using a loop
for i in grades:
  total += i
average = total /len(grades)

#2. calculate the average
if average >= 70:
  print("Pass")
else:
  print("Fail")

print("Average: ", average)

"""# 1. 2. Structured Programming  

## Brief Explanation
it sums up the grades and divides it by the ammount of grades before returning the average and if it passed

## Code Example
Complete the steps
"""

def calculate_average(grades):
    total = 0
    for g in grades:
        total += g
    return total / len(grades)

def determine_status(avg):
    if avg >= 60:
        return "Pass"
    else:
        return "Fail"

# Main program
grades = [85, 72, 90, 65]
avg = calculate_average(grades)
status = determine_status(avg)
print(f"Average: {avg:.1f} = {status}")

"""# Reflection

**What did you learn from this approach and how does it compare to others?**

i learnt that just because a programming type user different words, it can do the same if looked at from the right approach

# 1. 3. Modular Programming  

## Brief Explanation
it creates two other files for both the grades and the status before printing it
## Code Example
Complete the steps
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile grades_module.py
# 
# def average(grades):
#     return sum(grades) / len(grades)
# 
# def validate(grades):
#     return all(0 <= g <= 100 for g in grades)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile report_module.py
# 
# def status(avg):
#     return "Pass" if avg >= 60 else "Fail"
# 
# def report(name, avg, sts):
#     return f"{name}: {avg:.1f} → {sts}"

import grades_module as gm
import report_module as rm

name = "Ana"
grades = [85, 72, 90, 65]

if gm.validate(grades):
    avg = gm.average(grades)
    sts = rm.status(avg)
    print(rm.report(name, avg, sts))
else:
    print("Invalid grades — must be between 0 and 100")

"""# Reflection

**What did you learn from this approach and how does it compare to others?**

that there are definitively easier ways to code than this

# 1. 4. Object-Oriented Programming (OOP)

## Brief Explanation
it gets the name and the grades before doing the average and printing out if it passed
## Code Example
Complete the steps
"""

class Student:
    def __init__(self, name):
        self.name = name
        self.grades = []

    def add_grade(self, grade):
        self.grades.append(grade)

    def average(self):
        if not self.grades:
            return 0
        return sum(self.grades) / \
               len(self.grades)

    def status(self):
        avg = self.average()
        return "Pass" if avg >= 60 else "Fail"

    def report(self):
        return (f"{self.name}: "
                f"{self.average():.1f} → "
                f"{self.status()}")

# Usage
s = Student("Luis")
for g in [85, 72, 90, 65]:
    s.add_grade(g)
print(s.report())

"""# Reflection

**What did you learn from this approach and how does it compare to others?**

That i need to understand other programming languages and the way they work, that just because it's defined diferently and structured diferently doesnt mean it's impossible to use

# 1. 5. Functional programming

## Brief Explanation
it shows which ones pass and which ones dont
## Code Example
Complete the steps
"""

from functools import reduce

# Pure functions — no side effects
average = lambda gs: (
    reduce(lambda a, b: a + b, gs) / len(gs)
)

status = lambda avg: (
    "Pass" if avg >= 60 else "Fail"
)

evaluate = lambda name, gs: {
    "name": name,
    "average": average(gs),
    "status": status(average(gs))
}

# Process multiple students
students = [
    ("Mia",  [85, 72, 90]),
    ("Tom",  [45, 50, 55]),
]

results = list(map(
    lambda s: evaluate(*s),
    students
))

passing = list(filter(
    lambda r: r["status"] == "Pass",
    results
))

print(results)
print(passing)

"""# Reflection

**What did you learn from this approach and how does it compare to others?**

feels more confusing, need to learn more about lambda
"""